import type { IntelligenceSourceDefinition } from './registry';

export const SOURCE_REGISTRY: IntelligenceSourceDefinition[] = [
  {
    id: 'adsb-lol',
    name: 'ADSB.lol',
    publisher: 'ADSB.lol Community',
    category: 'aviation',
    baseUrl: 'https://api.adsb.lol',
    sourceType: 'specialist-source',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 15,
    requestTimeoutMs: 12000,
    maximumRetries: 2,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 120,
    costProfile: { tier: 'free-keyless', requiredForCore: false, attributionRequired: true },
    licence: 'ODbL',
    attribution: 'ADSB.lol',
    reliabilityPrior: 0.70,
  },
  {
    id: 'usgs-earthquake',
    name: 'USGS Earthquake Hazards Program',
    publisher: 'United States Geological Survey',
    category: 'geospatial',
    baseUrl: 'https://earthquake.usgs.gov',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 60,
    requestTimeoutMs: 10000,
    maximumRetries: 2,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 300,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    licence: 'Public Domain (US Government)',
    reliabilityPrior: 0.92,
  },
  {
    id: 'nasa-firms',
    name: 'NASA FIRMS',
    publisher: 'NASA',
    category: 'geospatial',
    baseUrl: 'https://firms.modaps.eosdis.nasa.gov',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: ['FIRMS_API_KEY'],
    pollingIntervalSeconds: 300,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'exponential',
    expectedContentType: ['text/csv'],
    stalenessThresholdSeconds: 600,
    costProfile: { tier: 'free-registration', requiredForCore: false },
    reliabilityPrior: 0.88,
  },
  {
    id: 'open-meteo-marine',
    name: 'Open-Meteo Marine',
    publisher: 'Open-Meteo',
    category: 'geospatial',
    baseUrl: 'https://marine-api.open-meteo.com',
    sourceType: 'specialist-source',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 1800,
    requestTimeoutMs: 10000,
    maximumRetries: 1,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 3600,
    costProfile: { tier: 'free-keyless', requiredForCore: false, attributionRequired: true },
    attribution: 'Open-Meteo',
    reliabilityPrior: 0.75,
  },
  {
    id: 'aisstream',
    name: 'AISstream.io',
    publisher: 'aisstream.io',
    category: 'maritime',
    baseUrl: 'wss://stream.aisstream.io',
    sourceType: 'specialist-source',
    enabledByDefault: true,
    requiredEnvironmentVariables: ['AISSTREAM_API_KEY'],
    pollingIntervalSeconds: 5,
    requestTimeoutMs: 30000,
    maximumRetries: 5,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 300,
    costProfile: { tier: 'free-registration', requiredForCore: false },
    reliabilityPrior: 0.75,
  },
  {
    id: 'lovin-malta',
    name: 'Lovin Malta',
    publisher: 'Lovin Malta',
    category: 'news',
    baseUrl: 'https://lovinmalta.com',
    sourceType: 'established-media',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 900,
    requestTimeoutMs: 10000,
    maximumRetries: 1,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 3600,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.75,
  },
  {
    id: 'newsbook',
    name: 'Newsbook',
    publisher: 'Newsbook',
    category: 'news',
    baseUrl: 'https://newsbook.com.mt',
    sourceType: 'established-media',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 900,
    requestTimeoutMs: 10000,
    maximumRetries: 1,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 3600,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.75,
  },
  {
    id: 'tvm-news',
    name: 'TVM News',
    publisher: 'TVM (Malta Public Broadcasting)',
    category: 'news',
    baseUrl: 'https://tvmnews.mt',
    sourceType: 'established-media',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 900,
    requestTimeoutMs: 10000,
    maximumRetries: 1,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 3600,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.75,
  },
  {
    id: 'council-eu-rss',
    name: 'Council of the EU — Press Releases',
    publisher: 'Council of the European Union',
    category: 'eu-policy',
    baseUrl: 'https://www.consilium.europa.eu',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 900,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 7200,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.95,
  },
  {
    id: 'eu-sanctions',
    name: 'EU Consolidated Sanctions List',
    publisher: 'European Commission',
    category: 'sanctions',
    baseUrl: 'https://ec.europa.eu',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 21600,
    requestTimeoutMs: 30000,
    maximumRetries: 3,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/xml'],
    stalenessThresholdSeconds: 86400,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.95,
  },
  {
    id: 'eeas',
    name: 'European External Action Service',
    publisher: 'EEAS',
    category: 'diplomatic',
    baseUrl: 'https://www.eeas.europa.eu',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 1800,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 7200,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.92,
  },
  {
    id: 'gdacs',
    name: 'GDACS',
    publisher: 'European Commission / United Nations',
    category: 'humanitarian',
    baseUrl: 'https://www.gdacs.org',
    sourceType: 'international-organisation',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 600,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml', 'application/json'],
    stalenessThresholdSeconds: 3600,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.92,
  },
  {
    id: 'reliefweb',
    name: 'ReliefWeb',
    publisher: 'OCHA / United Nations',
    category: 'humanitarian',
    baseUrl: 'https://api.reliefweb.int',
    sourceType: 'international-organisation',
    enabledByDefault: true,
    requiredEnvironmentVariables: ['RELIEFWEB_APP_NAME'],
    pollingIntervalSeconds: 900,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 7200,
    costProfile: { tier: 'free-registration', requiredForCore: false, attributionRequired: true },
    reliabilityPrior: 0.88,
  },
  {
    id: 'un-news',
    name: 'UN News',
    publisher: 'United Nations',
    category: 'multilateral',
    baseUrl: 'https://news.un.org',
    sourceType: 'international-organisation',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 1800,
    requestTimeoutMs: 15000,
    maximumRetries: 2,
    backoffStrategy: 'fixed',
    expectedContentType: ['application/rss+xml'],
    stalenessThresholdSeconds: 7200,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.92,
  },
  {
    id: 'world-bank',
    name: 'World Bank Indicators API',
    publisher: 'World Bank',
    category: 'economic',
    baseUrl: 'https://api.worldbank.org/v2',
    sourceType: 'international-organisation',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 86400,
    requestTimeoutMs: 30000,
    maximumRetries: 3,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 604800,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.92,
  },
  {
    id: 'eurostat',
    name: 'Eurostat',
    publisher: 'European Commission',
    category: 'economic',
    baseUrl: 'https://ec.europa.eu/eurostat',
    sourceType: 'official-primary',
    enabledByDefault: true,
    requiredEnvironmentVariables: [],
    pollingIntervalSeconds: 43200,
    requestTimeoutMs: 30000,
    maximumRetries: 3,
    backoffStrategy: 'exponential',
    expectedContentType: ['application/json'],
    stalenessThresholdSeconds: 604800,
    costProfile: { tier: 'free-keyless', requiredForCore: false },
    reliabilityPrior: 0.92,
  },
];

export function getSourceDefinition(id: string): IntelligenceSourceDefinition | undefined {
  return SOURCE_REGISTRY.find(s => s.id === id);
}

export function getSourcesByCategory(category: string): IntelligenceSourceDefinition[] {
  return SOURCE_REGISTRY.filter(s => s.category === category);
}

export function getSourcesWithKeyRequirements(): IntelligenceSourceDefinition[] {
  return SOURCE_REGISTRY.filter(s => s.requiredEnvironmentVariables.length > 0);
}
