import { NextResponse } from 'next/server';

const DOCS = {
  title: 'Malta OSINT — API Reference',
  version: '1.0.0',
  baseUrl: 'https://malta-osint.vercel.app/api',
  endpoints: [
    {
      path: '/config',
      methods: ['GET'],
      description: 'Returns client-safe environment variable names (values masked). Used by the frontend to obtain API keys for WebSocket connections.',
      auth: 'none',
      cache: 'no-cache',
      responseShape: { values: 'Record<string, string>' },
    },
    {
      path: '/malta/live',
      methods: ['GET'],
      description: 'Aggregated live intelligence for Malta: flights, marine conditions, seismic events, fires, news, and source health metadata.',
      auth: 'none',
      cache: 'public, s-maxage=15, stale-while-revalidate=45',
      responseShape: { timestamp: 'ISO8601', bbox: 'object', aviation: 'object', maritime: 'object', environment: 'object', intelligence: 'object', meta: 'object' },
    },
    {
      path: '/ais/vessels',
      methods: ['GET'],
      description: 'AIS vessel positions worldwide. Fetched from VesselAPI.com REST API. Returns vessels with MMSI, position, speed, heading, and metadata.',
      auth: 'VESSEL_API_KEY (env)',
      cache: 'no-cache, no-store',
      responseShape: { vessels: 'Vessel[]', count: 'number', connected: 'boolean', error: 'string|null', timestamp: 'number' },
    },
    {
      path: '/flights',
      methods: ['GET'],
      description: 'Real-time aircraft positions from adsb.lol (no API key required). Multiple regional queries aggregated.',
      auth: 'none',
      cache: 'public, s-maxage=30',
      responseShape: { flights: 'object[]', total: 'number', sources: 'string[]' },
    },
    {
      path: '/maritime',
      methods: ['GET'],
      description: 'Real-time AIS vessel tracking via aisstream.io WebSocket + static global ports. Cached in-memory with 10-min stale timeout.',
      auth: 'AIS_API_KEY (env, for WebSocket)',
      cache: 'no-cache',
      responseShape: { ships: 'object[]', ports: 'object[]', total: 'number' },
    },
    {
      path: '/fires',
      methods: ['GET'],
      description: 'Active fire detections from NASA FIRMS (VIIRS + MODIS). GeoJSON FeatureCollection.',
      auth: 'FIRMS_API_KEY (env)',
      cache: 'public, s-maxage=300',
      responseShape: { type: '"FeatureCollection"', features: 'FireFeature[]' },
    },
    {
      path: '/earthquakes',
      methods: ['GET'],
      description: 'Seismic events from USGS (last 24h, M2.5+). Returns GeoJSON FeatureCollection.',
      auth: 'none',
      cache: 'public, s-maxage=120',
      responseShape: { type: '"FeatureCollection"', features: 'EarthquakeFeature[]' },
    },
    {
      path: '/weather',
      methods: ['GET'],
      description: 'Active natural events from NASA EONET + NOAA/NWS alerts. Tracks storms, volcanoes, sea ice, and U.S. weather alerts.',
      auth: 'none',
      cache: 'public, s-maxage=300',
      responseShape: { events: 'object[]', alerts: 'object[]' },
    },
    {
      path: '/marine',
      methods: ['GET'],
      description: 'Live marine weather for Malta area from Open-Meteo Marine API: wave height, direction, period, SST, currents.',
      auth: 'none',
      cache: 'public, s-maxage=300',
      responseShape: { conditions: 'object', meta: 'object' },
    },
    {
      path: '/satellites',
      methods: ['GET'],
      description: 'Satellite TLE data from Celestrak + Space-Track.org with fallbacks.',
      auth: 'optional (Space-Track credentials in env)',
      cache: 'public, s-maxage=3600',
      responseShape: { satellites: 'object[]', sources: 'string[]' },
    },
    {
      path: '/space-weather',
      methods: ['GET'],
      description: 'Solar activity data from NOAA SWPC: planetary K-index, alerts, solar wind, radio flux.',
      auth: 'none',
      cache: 'public, s-maxage=300',
      responseShape: { kpIndex: 'object[]', alerts: 'object[]', solarWind: 'object', radioFlux: 'object' },
    },
    {
      path: '/news',
      methods: ['GET'],
      description: 'OSINT news from Telegram intelligence feeds with failsafe fallback. Returns deduplicated articles.',
      auth: 'none',
      cache: 'public, s-maxage=120',
      responseShape: { articles: 'object[]', sources: 'string[]' },
    },
    {
      path: '/live-news',
      methods: ['GET'],
      description: 'Malta news from RSS feeds (Lovin Malta, Newsbook, TVM News). Parsed and sorted by date.',
      auth: 'none',
      cache: 'public, s-maxage=120, stale-while-revalidate=300',
      responseShape: { news: 'object[]', total: 'number' },
    },
    {
      path: '/air-quality',
      methods: ['GET'],
      description: 'Global air quality data from OpenAQ API. Filterable by location.',
      auth: 'none',
      cache: 'public, s-maxage=300',
      responseShape: { results: 'object[]', meta: 'object' },
    },
    {
      path: '/cctv',
      methods: ['GET'],
      description: 'Worldwide public CCTV camera feeds aggregated from multiple directories.',
      auth: 'none',
      cache: 'public, s-maxage=3600',
      responseShape: { cameras: 'object[]', total: 'number' },
    },
    {
      path: '/infrastructure',
      methods: ['GET'],
      description: 'Critical global infrastructure: nuclear power plants with location, status, and reactor details.',
      auth: 'none',
      cache: 'public, s-maxage=86400',
      responseShape: { facilities: 'object[]', total: 'number' },
    },
    {
      path: '/country-risk',
      methods: ['GET'],
      description: 'Multi-signal country risk scoring inspired by WorldMonitor methodology.',
      auth: 'none',
      cache: 'public, s-maxage=3600',
      responseShape: { countries: 'object[]' },
    },
    {
      path: '/cyber-threats',
      methods: ['GET'],
      description: 'Cyber threat intelligence from CISA KEV, MITRE CVE, and other feeds.',
      auth: 'none',
      cache: 'public, s-maxage=600',
      responseShape: { vulnerabilities: 'object[]', threats: 'object[]' },
    },
    {
      path: '/frontlines',
      methods: ['GET'],
      description: 'Live warfront GeoJSON from DeepState Map (Ukraine conflict). Returns GeoJSON FeatureCollection.',
      auth: 'none',
      cache: 'public, s-maxage=600',
      responseShape: 'GeoJSON FeatureCollection',
    },
    {
      path: '/gdelt',
      methods: ['GET'],
      description: 'Global Events from GDELT Project. Returns recent news events, conflict monitoring, and media intelligence.',
      auth: 'none',
      cache: 'public, s-maxage=300',
      responseShape: { articles: 'object[]', total: 'number' },
    },
    {
      path: '/markets',
      methods: ['GET'],
      description: 'Financial market data: defense stocks, commodities, indices relevant to geopolitical analysis.',
      auth: 'none',
      cache: 'public, s-maxage=60',
      responseShape: { indices: 'object[]', commodities: 'object[]', defense: 'object[]' },
    },
    {
      path: '/analytics',
      methods: ['GET'],
      description: 'Platform analytics: request counts, active users, source health aggregations.',
      auth: 'none',
      cache: 'public, s-maxage=60',
      responseShape: { requests: 'number', sources: 'object' },
    },
    {
      path: '/health',
      methods: ['GET'],
      description: 'Platform health check. Returns status of all upstream dependencies and data sources.',
      auth: 'none',
      cache: 'no-cache',
      responseShape: { status: '"ok"|"degraded"|"down"', sources: 'object[]', uptime: 'number' },
    },
    {
      path: '/stats',
      methods: ['GET'],
      description: 'Aggregated counts from all live data sources. Used for dashboard counters.',
      auth: 'none',
      cache: 'public, s-maxage=15',
      responseShape: { flights: 'number', vessels: 'number', fires: 'number', earthquakes: 'number', news: 'number' },
    },
    {
      section: 'OSINT Tools',
      endpoints: [
        {
          path: '/osint/dns',
          methods: ['GET'],
          description: 'DNS record lookup (A, AAAA, MX, NS, TXT, CNAME, SOA).',
          params: { domain: 'string (required)', type: 'string (optional, default: A)' },
        },
        {
          path: '/osint/whois',
          methods: ['GET'],
          description: 'WHOIS domain registration lookup.',
          params: { domain: 'string (required)' },
        },
        {
          path: '/osint/ip',
          methods: ['GET'],
          description: 'IP geolocation and threat intelligence lookup.',
          params: { ip: 'string (required)' },
        },
        {
          path: '/osint/bgp',
          methods: ['GET'],
          description: 'BGP routing and ASN lookup.',
          params: { query: 'string (required) — ASN, IP, or prefix' },
        },
        {
          path: '/osint/certs',
          methods: ['GET'],
          description: 'SSL/TLS certificate transparency search via crt.sh.',
          params: { domain: 'string (required)' },
        },
        {
          path: '/osint/cve',
          methods: ['GET'],
          description: 'CVE vulnerability lookup and search.',
          params: { id: 'string (optional)', search: 'string (optional)' },
        },
        {
          path: '/osint/shodan',
          methods: ['GET'],
          description: 'Shodan device search (requires SHODAN_API_KEY).',
          params: { query: 'string (required)' },
        },
        {
          path: '/osint/github',
          methods: ['GET'],
          description: 'GitHub OSINT: repository and user reconnaissance.',
          params: { query: 'string (required)' },
        },
        {
          path: '/osint/sweep',
          methods: ['GET'],
          description: 'Port scan via local scanner service (requires SCANNER_URL + SCANNER_KEY).',
          params: { target: 'string (required)', ports: 'string (optional)' },
        },
        {
          path: '/osint/phone',
          methods: ['GET'],
          description: 'Phone number lookup and carrier information.',
          params: { number: 'string (required)' },
        },
        {
          path: '/osint/mac',
          methods: ['GET'],
          description: 'MAC address vendor lookup.',
          params: { mac: 'string (required)' },
        },
        {
          path: '/osint/leaks',
          methods: ['GET'],
          description: 'Data breach and credential leak search.',
          params: { email: 'string (required)' },
        },
        {
          path: '/osint/sanctions',
          methods: ['GET'],
          description: 'Sanctions and PEP (Politically Exposed Persons) screening.',
          params: { name: 'string (required)' },
        },
        {
          path: '/osint/threats',
          methods: ['GET'],
          description: 'Threat intelligence feed: IP reputation, domain reputation, malware analysis.',
          params: { q: 'string (required) — IP, domain, or hash' },
        },
      ],
    },
    {
      section: 'Intelligence Platform',
      endpoints: [
        {
          path: '/intelligence/brief',
          methods: ['GET'],
          description: 'Daily intelligence briefing. Aggregates top events, sources, and AI-generated summary.',
        },
        {
          path: '/intelligence/events',
          methods: ['GET', 'POST'],
          description: 'Intelligence events CRUD. Lists, filters, and creates intelligence events with STIX-like metadata.',
          params: { page: 'number', limit: 'number', severity: 'number', country: 'string' },
        },
        {
          path: '/intelligence/countries',
          methods: ['GET'],
          description: 'Country intelligence profiles with risk scores, events, and source health.',
        },
        {
          path: '/intelligence/eu',
          methods: ['GET'],
          description: 'EU-specific intelligence: policy tracking, sanctions, and multilateral analysis.',
        },
        {
          path: '/intelligence/economic',
          methods: ['GET'],
          description: 'Economic security indicators: trade data, sanctions impact, strategic dependencies.',
        },
        {
          path: '/intelligence/sanctions',
          methods: ['GET'],
          description: 'EU consolidated sanctions list and OpenSanctions integration.',
        },
        {
          path: '/intelligence/source-health',
          methods: ['GET'],
          description: 'Health check for all intelligence data sources with latency, error rates, and staleness.',
        },
        {
          path: '/intelligence/review',
          methods: ['GET', 'POST'],
          description: 'Human-in-the-loop review queue for AI-generated intelligence items.',
        },
        {
          path: '/intelligence/ingest',
          methods: ['POST'],
          description: 'Ingestion endpoint for external intelligence feeds. Accepts STIX-like entity data.',
        },
      ],
    },
    {
      section: 'Smart System (AI Engine)',
      endpoints: [
        {
          path: '/ai/analyze',
          methods: ['POST'],
          description: 'AI analysis of intelligence data using configured LLM (Gemini/Ollama).',
          params: { prompt: 'string (required)', context: 'object (optional)' },
        },
        {
          path: '/ai/briefing',
          methods: ['GET'],
          description: 'AI-generated daily intelligence briefing.',
        },
        {
          path: '/smart-system/status',
          methods: ['GET'],
          description: 'Smart system status: module health, active apps, pipeline state.',
        },
        {
          path: '/smart-system/run',
          methods: ['POST'],
          description: 'Execute a smart system app (e.g., asset tracking, threat correlation).',
        },
        {
          path: '/smart-system/recommendations',
          methods: ['GET'],
          description: 'AI-generated recommendations based on current intelligence posture.',
        },
        {
          path: '/smart-system/audit',
          methods: ['GET'],
          description: 'Audit log of all smart system actions and decisions.',
        },
        {
          path: '/smart-system/coa',
          methods: ['POST'],
          description: 'Course of Action analysis: AI-generated response options for identified threats.',
        },
      ],
    },
    {
      section: 'SDK & Data Pipeline',
      endpoints: [
        {
          path: '/sdk/ingest',
          methods: ['POST'],
          description: 'SDK ingestion endpoint. Accepts normalized ThirdEye entities for custom integrations.',
          auth: 'SDK_INGEST_KEY (env, header: x-sdk-key)',
        },
        {
          path: '/sdk/stream',
          methods: ['GET'],
          description: 'Server-Sent Events (SSE) stream of real-time entity updates for SDK clients.',
        },
      ],
    },
  ],
};

export async function GET() {
  return NextResponse.json(DOCS, {
    headers: {
      'Cache-Control': 'public, s-maxage=3600',
      'Access-Control-Allow-Origin': '*',
    },
  });
}
